# Generated by Django 5.0.1 on 2024-01-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_team', models.ImageField(upload_to='Media/ourTeam')),
                ('ourTeam_name', models.CharField(max_length=100, null=True)),
                ('ourTeamabout', models.TextField()),
            ],
        ),
    ]
